language: node_js
node_js:
  - '11'
script:
  - yarn lint
  - yarn test
  - yarn build

env:
  global:
    secure: iW7hXg1UaHlNIBwH/QcM5tNf/f/AhLPZyoy0cDjevyHseo2T/imBT5IrIgXzISUjSkazzUfkibZNmyaFH4BrhVarp5AoT6DMHlbeKJohJJ3xHxIU7+fIiUXkuiVTd92UxCh0P4isQNrG4YHnKzPOEi4NtoxLA33x03R74JvHJnM0jACSu2YXkd0SW/wZt8OrL9ZUzD1x/b+q2OAOPsoYXE7W8ibskcn45kF46VHn2svUnsG5oNGqX+epYa51HG4KzFkxNDj8LjM7SaSUQyGkXfkshQIfwKcEmVMrlAX6eGB2syqUCyeVdTIaBZP94NgDpY9w+Hh29EEFfMtF1VMPOgNTZTlVMM5KrhvkfmN4Zn0OWObQPN5TiJSkLdsSeDtWXWbZ/KtL7FBCxqYHn/JwH5Oxab0lSurDk5NaOLe9dF98gXNpCaSAsEphqeTLBpnXPNe2biWgyJnCIWYYhJWT1v+AOOj5ziklOxrCiHALvXWMQ0mdi6XKordkAlONeXUBJUrc7ORtgPJGE4lgDmFCl3qfJczQ7BUaucvxIC+8Yf3Wtf3Lm+DFNogxpU9rReMh6BLr8+KL63WyRlqZq66vIRnzsKd+im6ZCo+TRxdWuJblq7N+aRGD5N4bKO37Il7DfTBG87ULvvGFQjvfxGhXMW75ABiSxEpkj4dAigkPr8s=
