language: node_js
node_js:
- '6'
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- yarn run lint
- yarn run build
after_script: greenkeeper-lockfile-upload